# Generated by Django 2.2.3 on 2020-02-14 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0005_imagemodel_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createdDate',
            field=models.DateField(default=datetime.date(2020, 2, 14)),
        ),
    ]
