# Generated by Django 2.2.3 on 2020-02-19 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0010_auto_20200218_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createdDate',
            field=models.DateField(default=datetime.date(2020, 2, 19)),
        ),
        migrations.AlterField(
            model_name='renditionimages',
            name='real_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='imagesapp.ImageSourceModel'),
        ),
    ]
