# Generated by Django 2.2.3 on 2020-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0002_auto_20200214_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='tagname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
