# Generated by Django 2.2.3 on 2020-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0003_auto_20200214_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='tag',
            field=models.TextField(default='', null=True),
        ),
    ]
