# Generated by Django 2.2.3 on 2020-02-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0007_auto_20200216_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='tag',
            field=models.ManyToManyField(to='imagesapp.TagsModel'),
        ),
    ]
