# Generated by Django 2.2.3 on 2020-02-18 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0008_imagemodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='imagesrc',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='createdDate',
            field=models.DateField(default=datetime.date(2020, 2, 18)),
        ),
        migrations.AlterField(
            model_name='renditionimages',
            name='real_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='imagesapp.ImageModel'),
        ),
        migrations.CreateModel(
            name='ImageSourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesrc', models.ImageField(upload_to='documents/')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagesapp.ImageModel')),
            ],
        ),
    ]
