# Generated by Django 2.2.3 on 2020-02-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0009_auto_20200218_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='imagesourcemodel',
            name='tag',
            field=models.ManyToManyField(to='imagesapp.TagsModel'),
        ),
        migrations.AlterField(
            model_name='imagesourcemodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imagesapp.ImageModel'),
        ),
    ]
