# Generated by Django 2.2.5 on 2020-02-22 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0011_auto_20200219_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createdDate',
            field=models.DateField(default=datetime.date(2020, 2, 22)),
        ),
    ]
