# Generated by Django 2.1.5 on 2020-02-23 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0012_auto_20200222_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='createdDate',
            field=models.DateField(default=datetime.date(2020, 2, 23)),
        ),
    ]
